-- SQL generated by pgAdmin showing db creation
-- (may not reflect all changes made)

CREATE TABLE public."States"
(
    "stateCode" character varying(2) NOT NULL,
    "stateName" character varying(155) NOT NULL,
    PRIMARY KEY ("stateCode")
);

ALTER TABLE public."States"
    OWNER to postgres;

COMMENT ON TABLE public."States"
    IS 'Holds state names and code data';

CREATE TABLE public."Sources"
(
    "sourceCode" character varying(2) NOT NULL,
    "sourceName" character varying(155) NOT NULL,
    PRIMARY KEY ("sourceCode")
)

TABLESPACE pg_default;

ALTER TABLE public."Sources"
    OWNER to postgres;


CREATE TABLE public."Sectors"
(
    "sectorCode" character varying(2) NOT NULL,
    "sectorName" character varying(155) NOT NULL,
    description character varying(455),
    PRIMARY KEY ("sectorCode")
)

TABLESPACE pg_default;

ALTER TABLE public."Sectors"
    OWNER to postgres;

COMMENT ON TABLE public."Sectors"
    IS 'Reference table for primary energy sources';


CREATE TABLE public."ProdCodes"
(
    "msnCode" character varying(8) NOT NULL,
    description character varying(255),
    units character varying(80) NOT NULL,
    PRIMARY KEY ("msnCode")
)

TABLESPACE pg_default;

ALTER TABLE public."ProdCodes"
    OWNER to postgres;


    CREATE TABLE public."ConCodes"
(
    "msnCode" character varying(8) NOT NULL,
    description character varying(155),
    units character varying(80) NOT NULL,
    PRIMARY KEY ("msnCode")
)

TABLESPACE pg_default;

ALTER TABLE public."ConCodes"
    OWNER to postgres;


CREATE TABLE public."Years"
(
    year character varying(8) NOT NULL,
    PRIMARY KEY (year)
)

TABLESPACE pg_default;

ALTER TABLE public."Years"
    OWNER to postgres;


CREATE TABLE public."Consumption"
(
    "sectorCode" character varying(2) NOT NULL,
    "stateCode" character varying(2) NOT NULL,
    "sourceCode" character varying(2) NOT NULL,
    year character varying(8) NOT NULL,
    "msnCode" character varying(8) NOT NULL,
    "energyConsumed" integer NOT NULL,
    CONSTRAINT cons_id PRIMARY KEY ("sectorCode", "stateCode", "sourceCode", year),
    CONSTRAINT sector_key FOREIGN KEY ("sectorCode")
        REFERENCES public."Sectors" ("sectorCode") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT state_key FOREIGN KEY ("stateCode")
        REFERENCES public."States" ("stateCode") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT source_key FOREIGN KEY ("sourceCode")
        REFERENCES public."Sources" ("sourceCode") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT year_key FOREIGN KEY (year)
        REFERENCES public."Years" (year) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT msn_code_key FOREIGN KEY ("msnCode")
        REFERENCES public."ConCodes" ("msnCode") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);

ALTER TABLE public."Consumption"
    OWNER to postgres;


CREATE TABLE public."Production"
(
    "stateCode" character varying(2) NOT NULL,
    "sourceCode" character varying(2) NOT NULL,
    year character varying(8) NOT NULL,
    "msnCode" character varying(8) NOT NULL,
    "energyProduced" integer NOT NULL,
    CONSTRAINT prod_id PRIMARY KEY ("stateCode", "sourceCode", year),
    CONSTRAINT state_key FOREIGN KEY ("stateCode")
        REFERENCES public."States" ("stateCode") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT source_key FOREIGN KEY ("sourceCode")
        REFERENCES public."Sources" ("sourceCode") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT year_key FOREIGN KEY (year)
        REFERENCES public."Years" (year) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT msn_code_key FOREIGN KEY ("msnCode")
        REFERENCES public."ProdCodes" ("msnCode") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."Production"
    OWNER to postgres;